Repository AY2324S2-CS2103-F09-2/tp, pull requests merged in 2024-03, with the labels that each got.

#23 Update AboutUs.md for milestone v1.1
  docs/AboutUs.md
  docs/images/zhiwei1010.png
Labels: type.Documentation

#29 V1.1 acknowledgement + Project Links table in Home Page
  docs/index.md
Labels: type.Documentation, priority.High, v1.1

#33 doc: Update About Us
  docs/AboutUs.md
  docs/images/sherissetjw.PNG
Labels: type.Documentation, priority.High, v1.1

#32 Adapt target user profile and value proposition to fit PatientSync
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.High, v1.1

#38 Add Nurse user stories for PatientSync
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.High, v1.1

#37 Update non-functional requirements to match Patientsync
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.High, v1.1

#40 Add use cases in Developer Guide
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.High, v1.1

#48 fix: Change extension to lower case
  docs/AboutUs.md
  docs/images/sherissetjw.png
Labels: type.Documentation, priority.High, type.Bug

#57 fix: Null errors on running
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PatientListPanel.fxml
Labels: priority.High, type.Bug, severity.High

#58 V1.2 add tags backend
  README.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/index.md
  docs/stylesheets/main.css
  src/main/java/seedu/address/logic/commands/AddTagsCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddTagsCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/patient/EditPatientDescriptor.java
  src/test/java/seedu/address/logic/commands/AddTagsCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPatientDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddTagsCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPatientDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PatientUtil.java
Labels: type.Story, priority.High

#60 Feat/add important dates for patients
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddImportantDateCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddImportantDateParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/patient/EditPatientDescriptor.java
  src/main/java/seedu/address/model/patient/ImportantDate.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/AddImportantDateCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPatientDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddImportantDateParserTest.java
  src/test/java/seedu/address/logic/parser/AddTagsCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/patient/ImportantDateTest.java
  src/test/java/seedu/address/model/patient/PatientTest.java
  src/test/java/seedu/address/testutil/EditPatientDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PatientBuilder.java
Labels: type.Story, priority.High

#62 V1.2 Update Docs and dependencies
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/index.md
  src/main/java/seedu/address/logic/commands/AddTagsCommand.java
  src/main/java/seedu/address/logic/parser/AddTagsCommandParser.java
  src/test/java/seedu/address/logic/parser/AddTagsCommandParserTest.java
Labels: type.Documentation, priority.High

#63 V1.2 Update Delete Command
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
Labels: priority.High

#67 Fix bug where Important Dates were not saved to the AddressBook.json, and cannot be shown in `list` command
  src/main/java/seedu/address/storage/JsonAdaptedImportantDate.java
  src/main/java/seedu/address/storage/JsonAdaptedPatient.java
  src/main/java/seedu/address/ui/PatientCard.java
  src/main/resources/view/PatientListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalPatientAddressBook.json
  src/test/java/seedu/address/storage/JsonAdaptedPatientTest.java
  src/test/java/seedu/address/testutil/PatientBuilder.java
  src/test/java/seedu/address/testutil/TypicalPatients.java
Labels: priority.High, type.Bug, severity.High

#65 V1.2 delete important dates: Logic & Test
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteImportantDateCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteImportantDateCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/test/java/seedu/address/logic/commands/DeleteImportantDateCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteImportantDateParserTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.Story, priority.High

#74 V1.2 add tags sequence diagram
  docs/DeveloperGuide.md
  docs/diagrams/addTagsSequenceDiagram.puml
Labels: type.Documentation, priority.High

#76 Fix errors in important dates validation and UI MESSAGE_SUCCESS display
  src/main/java/seedu/address/logic/commands/AddImportantDateCommand.java
  src/main/java/seedu/address/model/patient/ImportantDate.java
  src/test/java/seedu/address/logic/commands/AddImportantDateCommandTest.java
  src/test/java/seedu/address/model/patient/ImportantDateTest.java
Labels: priority.High, type.Bug

#72 v1.2 Edit Important Date
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditEventCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditEventCommandParser.java
  src/test/java/seedu/address/logic/commands/EditEventCommandTest.java
  src/test/java/seedu/address/logic/parser/EditEventCommandParserTest.java
Labels: priority.Medium

#82 Fix error in delete event command indexing
  src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
  src/test/java/seedu/address/logic/commands/DeleteEventCommandTest.java
Labels: priority.High, type.Bug, severity.High

#86 Add puml diagram and update DG for AddEvent
  docs/DeveloperGuide.md
  docs/diagrams/AddEventSequenceDiagram.puml
Labels: type.Documentation, priority.High

#88 v1.2 Add EditEventSequenceDiagram and update DeleteSequenceDiagram
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/EditEventSequenceDiagram.puml
Labels: priority.High

#89 Embed PlantUML Diagram for AddEventCommand in DG
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.Medium

#94 Docs: v1.2 Update Developer Guide for DeleteCommand
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.High

#96 Comment out DeleteTagsTimeSequenceDiagram in the DG
  docs/DeveloperGuide.md
  docs/_site/stylesheets/main.css
Labels: type.Documentation, priority.High

#99 Create DeleteTagsSequenceDiagram
  docs/DeveloperGuide.md
  docs/diagrams/AddTagsSequenceDiagram.puml
  docs/diagrams/DeleteTagsSequenceDiagram.puml
Labels: type.Documentation, priority.High

#114 v1.3 Patient Hospital Id issues
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FindSequenceDiagram.puml
  docs/images/findPatient12345Result.png
  docs/images/findPatientAlexBeckerResult.png
  src/main/java/seedu/address/model/patient/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/ui/PatientCard.java
  src/main/resources/view/PatientListCard.fxml
  src/test/java/seedu/address/model/patient/NameContainsKeywordsPredicateTest.java
Labels: type.Enhancement

#116 V1.3 tags enhancement
  build.gradle
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddTagsActivityDiagram.puml
  docs/diagrams/DeleteTagsActivityDiagram.puml
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/logic/commands/AddTagsCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTagsCommand.java
  src/main/java/seedu/address/logic/parser/AddTagsCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteTagsCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/logic/commands/AddTagsCommandTest.java
  src/test/java/seedu/address/logic/parser/AddTagsCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: type.Documentation, priority.High, type.Enhancement, type.Task

#117 Add a custom duplicate message when the user adds a duplicate event
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/model/patient/Event.java
  src/test/java/seedu/address/logic/commands/AddEventCommandTest.java
Labels: priority.Medium, type.Enhancement

#119 v1.3 custom message for duplicate events for EditEventCommand
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/EditEventCommand.java
  src/test/java/seedu/address/logic/commands/AddEventCommandTest.java
  src/test/java/seedu/address/logic/commands/EditEventCommandTest.java
Labels: priority.Medium

#120 Preserve Ordering for Events by Sorting them
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
  src/main/java/seedu/address/logic/commands/EditEventCommand.java
  src/main/java/seedu/address/model/patient/Event.java
  src/main/java/seedu/address/ui/PatientCard.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/patient/EventTest.java
  src/test/java/seedu/address/testutil/PatientBuilder.java
Labels: priority.High, type.Enhancement

#121 v1.3 Find Patient using Tags
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FindTagsSequenceDiagram.puml
  src/main/java/seedu/address/logic/commands/FindTagsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindTagsCommandParser.java
  src/main/java/seedu/address/model/patient/TagContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindTagsCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindTagsCommandParserTest.java
  src/test/java/seedu/address/model/patient/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/patient/TagContainsKeywordsPredicateTest.java
Labels: type.Story, priority.Medium

#128 Corrections to sample data
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.High, type.Bug

#136 Add event command activity diagram and lifeline note for all commands
  docs/DeveloperGuide.md
  docs/diagrams/AddEventActivityDiagram.puml
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/parser/AddEventCommandParserTest.java
Labels: type.Documentation, priority.High

#139 Add Screenshots for all features into UG
  docs/UserGuide.md
  docs/images/addEventResult.PNG
  docs/images/addPatientResult.png
  docs/images/addTagsResult.PNG
  docs/images/clearResult.PNG
  docs/images/deleteEventResult.PNG
  docs/images/deleteResult.PNG
  docs/images/deleteTagsResult.PNG
  docs/images/editEventResult.PNG
  docs/images/editPatientResult.PNG
  docs/images/findTagsResult.PNG
  docs/images/listResult.PNG
Labels: type.Documentation, priority.Medium

#141 v1.3 Fix Sequence Diagrams
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/FindTagsSequenceDiagram.puml
Labels: type.Documentation, priority.High

#143 Add logging and assertions for AddEventCommand
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
Labels: priority.Medium, type.Task

#146 Fix the Activity Diagram for AddEventCommand
  docs/diagrams/AddEventActivityDiagram.puml
Labels: type.Documentation, priority.High, type.Bug
