Repository AY2324S2-CS2103-F09-2/tp, pull requests merged in 2024-04, with the labels that each got.

#145 v1.3 Update EditEventCommand code quality and add EditEventActivityDiagram
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/EditEventActivityDiagram.puml
  src/main/java/seedu/address/logic/commands/EditEventCommand.java
  src/test/java/seedu/address/logic/commands/EditEventCommandTest.java
Labels: priority.High

#148 Fix ordering of AddEvent Activity Diagram
  docs/diagrams/AddEventActivityDiagram.puml
Labels: type.Documentation, priority.High, type.Bug

#150 V1.3 tags bug fixes
  src/main/java/seedu/address/logic/parser/AddTagsCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteTagsCommandParser.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/logic/parser/AddTagsCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteTagsCommandParserTest.java
Labels: priority.High, type.Bug

#152 v1.3 Add assert and log statements
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditEventCommand.java
  src/main/java/seedu/address/logic/commands/FindTagsCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditEventCommandParser.java
  src/main/java/seedu/address/logic/parser/FindTagsCommandParser.java
Labels: priority.High

#154 v1.3 Fix Documentation Bugs
  docs/diagrams/EditEventActivityDiagram.puml
  docs/images/addEventResult.png
  docs/images/addTagsResult.png
  docs/images/clearResult.png
  docs/images/deleteEventResult.png
  docs/images/deleteResult.png
  docs/images/deleteTagsResult.png
  docs/images/editEventResult.png
  docs/images/editPatientResult.png
  docs/images/findTagsResult.png
  docs/images/listResult.png
Labels: type.Documentation, priority.High, type.Bug

#155 Fix Event Bugs
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/patient/Event.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/test/java/seedu/address/logic/parser/AddEventCommandParserTest.java
  src/test/java/seedu/address/model/patient/EventTest.java
Labels: type.Documentation, priority.High, type.Bug, severity.High

#158 v1.3 Fix Invalid Prefix for EditEventCommand
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/EditEventCommandParser.java
  src/test/java/seedu/address/logic/parser/EditEventCommandParserTest.java
Labels: priority.High

#160 V1.3 sort command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/SortActivityDiagram.puml
  docs/diagrams/SortSequenceDiagram.puml
  docs/images/sortResult.png
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/patient/comparators/NameComparator.java
  src/main/java/seedu/address/model/patient/comparators/PreferredNameComparator.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
Labels: type.Story, priority.Medium

#165 V1.3 delete event improve code quality
  src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
  src/main/java/seedu/address/logic/parser/DeleteEventCommandParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.Medium, type.Enhancement

#161 v1.3 Refactor Patient info to Set
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/patient/EditPatientDescriptor.java
  src/main/java/seedu/address/model/patient/FamilyCondition.java
  src/main/java/seedu/address/model/patient/FoodPreference.java
  src/main/java/seedu/address/model/patient/Hobby.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedFamilyCondition.java
  src/main/java/seedu/address/storage/JsonAdaptedFoodPreference.java
  src/main/java/seedu/address/storage/JsonAdaptedHobby.java
  src/main/java/seedu/address/storage/JsonAdaptedPatient.java
  src/main/java/seedu/address/ui/PatientCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PatientListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePatientAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPatientAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPatientAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPatientDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/patient/FamilyConditionTest.java
  src/test/java/seedu/address/model/patient/FoodPreferenceTest.java
  src/test/java/seedu/address/model/patient/HobbyTest.java
  src/test/java/seedu/address/model/patient/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/patient/PatientTest.java
  src/test/java/seedu/address/model/patient/TagContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPatientTest.java
  src/test/java/seedu/address/testutil/EditPatientDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PatientBuilder.java
  src/test/java/seedu/address/testutil/PatientUtil.java
  src/test/java/seedu/address/testutil/TypicalPatients.java
Labels: priority.Medium, type.Enhancement

#168 v1.3 Update UserGuide
  docs/UserGuide.md
Labels: type.Documentation, priority.High

#170 Prevent Invalid Time Formats in Event Commands
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/EditEventCommand.java
  src/main/java/seedu/address/model/patient/Event.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/PatientCard.java
  src/test/data/JsonSerializableAddressBookTest/typicalPatientAddressBook.json
  src/test/java/seedu/address/logic/commands/AddEventCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditEventCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/patient/EventTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPatientTest.java
Labels: priority.High, type.Enhancement, type.Bug, severity.High

#172 V1.3 update all screenshots related to Ui to most updated Ui
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/addEventResult.png
  docs/images/addTagsResult.png
  docs/images/deleteEventResult.png
  docs/images/deletePatientResult.png
  docs/images/deleteResult.png
  docs/images/deleteTagsResult.png
  docs/images/editEventResult.png
  docs/images/editPatientResult.png
  docs/images/findPatientAlexAliResult.png
  docs/images/findPatientAlexBeckerResult.png
  docs/images/findTagsResult.png
  docs/images/listResult.png
  docs/images/sortResult.png
Labels: type.Documentation, priority.High

#167 v1.3 Fix EditCommand to disallow duplicated prefixes for Name, PreferredName and PID
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddActivityDiagram.puml
  docs/diagrams/EditActivityDiagram.puml
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: type.Documentation, priority.High, type.Bug

#175 Update Version number in MainApp
  src/main/java/seedu/address/MainApp.java
Labels: priority.Medium, type.Bug

#237 V1.4 - Event UG Fixes and Error Message Edit
  docs/UserGuide.md
  src/main/java/seedu/address/model/patient/Event.java
Labels: type.Documentation

#238 v1.4 User Guide and PE-D bugs fix
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/addEventResult.png
  docs/images/editEventResult.png
  docs/images/findPatientAlexAliResult.png
  docs/images/findPatientResult.png
  docs/images/findTagsResult.png
Labels: type.Documentation, priority.High, type.Bug

#239 v1.4 PED Documentation Bug Fixes
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/addPatientResult.png
  docs/images/editPatientResult.png
Labels: type.Documentation, priority.Medium, type.Bug

#242 Planned Enhancements for Event
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/model/patient/Event.java
Labels: type.Documentation, priority.High

#243 v1.4 Update Documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/clearResult.png
  docs/images/deletePatientResult.png
Labels: type.Documentation, priority.High

#244 v1.4 Planned Enhancement on PatientHospitalId and patient's Name
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.High, type.Enhancement

#247 Add Planned Enhancement for Standardised Error and Clean DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Documentation

#246 V1.4 dg improvements
  docs/DeveloperGuide.md
  docs/package-lock.json
  docs/package.json
Labels: type.Documentation, priority.Medium

#251 v1.4 Update Sample Add Command
  docs/UserGuide.md
Labels: type.Documentation, type.Bug, severity.Medium

#252 v1.4 Update Documentations
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DeleteActivityDiagram.puml
  docs/diagrams/EditEventActivityDiagram.puml
  docs/diagrams/FindActivityDiagram.puml
  docs/diagrams/FindTagsActivityDiagram.puml
Labels: type.Documentation, priority.Medium

#253 Logic: Add credit for code adaptation in comparator classes
  src/main/java/seedu/address/model/patient/comparators/NameComparator.java
  src/main/java/seedu/address/model/patient/comparators/PreferredNameComparator.java
Labels: priority.High, type.Task

#250 V1.4-Update use case in DG
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.High

#255 Docs: Update typo error in sort command specifications in UG
  docs/UserGuide.md
Labels: type.Documentation, severity.Medium

#256 v1.4 Standardise Format of Design Considerations on DG
  docs/DeveloperGuide.md
Labels: type.Documentation, type.Bug, severity.Low

#254 V1.4 DG Improvement
  docs/DeveloperGuide.md
  docs/diagrams/AddEventActivityDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DeleteEventActivityDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/SortActivityDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
Labels: type.Documentation, priority.High

#257 Clean up the Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
Labels: type.Documentation

#258 v1.4 Fix User Guide Bugs
  docs/UserGuide.md
Labels: type.Documentation, priority.High, type.Bug

#259 v1.4 Update Activity Diagram for Add and Edit Commands
  docs/diagrams/AddActivityDiagram.puml
  docs/diagrams/EditActivityDiagram.puml
Labels: type.Documentation, priority.Medium

#260 v1.4 Fix Developer Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddEventSequenceDiagram.puml
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/AddTagsSequenceDiagram.puml
  docs/diagrams/DeleteTagsSequenceDiagram.puml
  docs/diagrams/EditEventSequenceDiagram.puml
  docs/diagrams/EditSequenceDiagram.puml
  docs/diagrams/FindTagsSequenceDiagram.puml
Labels: type.Documentation, priority.High

#262 V1.4 dg improvements and minor bug fix
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
Labels: type.Documentation, severity.High

#263 V1.4 fix redirection links & class diagrams
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Documentation, severity.Medium

#264 Fix extra empty page in UG.
  docs/UserGuide.md
Labels: type.Documentation, priority.High

#266 V1.4 Updates to DG to prep for release
  docs/DeveloperGuide.md
Labels: type.Documentation, type.Task

#267 Add Exit, Help and Clear Commands to DG
  docs/DeveloperGuide.md
Labels: type.Documentation

#268 v1.4 Add page break for Developer Guide
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.High

#269 v1.4 Update page breaks
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.High

#272 v1.4 Update Version Number in MainApp for v1.4 release
  src/main/java/seedu/address/MainApp.java
Labels: priority.Medium, type.Task

#273 v1.4 UG and DG Documentation Fixes
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Documentation, type.Bug
